services:
  ddns-server:
    image: registry.cn-shanghai.aliyuncs.com/iproute/dnsapi-server-aliyun
    container_name: dnsapi-server-aliyun
    ports:
      - "8080:8080"
    volumes:
      - "./logs:/opt/app/logs"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTIONS=-Xmx64M
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - ACCESS_TOKEN_KEY=
      - ACCESS_TOKEN_LIST=
      - ENDPOINT=alidns.cn-shanghai.aliyuncs.com
      - ALIBABA_CLOUD_ACCESS_KEY_LIST=
      - DNS_API_DOMAIN_ACCESS_CONTROL_LIST=
      - DNS_API_EXCLUDE_RR_LIST=