quarkus:
  http:
    port: 8080
#  log:
#    handler-stdout: false
#    handler-file: false

service:
  accessTokenHeaderKey: ${ACCESS_TOKEN_KEY:access-token}
  accessTokenList: ${ACCESS_TOKEN_LIST:hello,ddns}

aliyun:
  endpoint: ${ENDPOINT:alidns.cn-shanghai.aliyuncs.com}
  accessKeyId: ${ALIBABA_CLOUD_ACCESS_KEY_ID:}
  accessKeySecret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET:}

dns-api:
  domainAcl: ${DNS_API_DOMAIN_ACCESS_CONTROL_LIST:}
  excludeRrList: ${DNS_API_EXCLUDE_RR_LIST:}